name: Go
on:
  push:
    branches: ["main"]
    tags:
      - "release*"
  pull_request:
    branches: ["main"]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
      - name: Build multi-OS binaries
        if: startsWith(github.ref, 'refs/tags/release')
        run: |
          GOOS=linux GOARCH=amd64 go build -o vyosexporter-linux-amd64
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/release')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_DEV }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
      - name: Upload Linux AMD64
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_DEV }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vyosexporter-linux-amd64
          asset_name: vyosexporter-linux-amd64
          asset_content_type: application/octet-stream
